language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
sudo: false
env:
  - TEST_SUITE=install
os:
  - linux
script: npm run-script test-all:cover
before_install:
  - npm config set spin false
install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional

after_script:
  - cat coverage/lcov.info | codeclimate
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
